---
- name: Reload sshd
  ansible.builtin.systemd:
    name: "{{ atomik_sshd_service | default('sshd') }}"
    state: reloaded

- name: Reload sysctl
  ansible.builtin.shell: "bash {{ inventory_dir }}/../../scripts/ansible/roles/security/handlers/reload_sysctl.sh"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload udev
  ansible.builtin.shell: "bash {{ inventory_dir }}/../../scripts/ansible/roles/security/handlers/reload_udev.sh"

- name: Apply tuned profile
  ansible.builtin.shell: "bash {{ inventory_dir }}/../../scripts/ansible/roles/security/handlers/apply_tuned_profile.sh"

- name: Enable thermald
  ansible.builtin.systemd:
    name: thermald
    state: started
    enabled: true

- name: Restart zram
  ansible.builtin.systemd:
    name: systemd-zram-setup@zram0.service
    state: restarted

- name: Enable swapfile service
  ansible.builtin.systemd:
    name: atomik-swapfile.service
    state: started
    enabled: true

- name: Enable swap unit
  ansible.builtin.systemd:
    name: var-swapfile.swap
    state: started
    enabled: true

- name: Reload journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Rebuild grub
  ansible.builtin.shell: "bash {{ inventory_dir }}/../../scripts/ansible/roles/security/handlers/rebuild_grub.sh"
