---
- name: Mask non-essential system services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  loop: "{{ atomik_masked_services }}"
  register: mask_result
  failed_when: mask_result is failed and 'Could not find the requested service' not in mask_result.msg
