---

- name: Set critical file permissions
  ansible.builtin.file:
    path: "{{ item.key }}"
    mode: "{{ item.value }}"
  loop: "{{ atomik_permissions | dict2items }}"
  loop_control:
    label: "{{ item.key }}={{ item.value }}"
