---

- name: Deploy swapfile service
  ansible.builtin.template:
    src: swapfile.service.j2
    dest: /etc/systemd/system/atomik-swapfile.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Enable swapfile service

- name: Deploy swapfile unit
  ansible.builtin.template:
    src: swapfile.unit.j2
    dest: /etc/systemd/system/var-swapfile.swap
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Enable swap unit
