---

- name: Enable tuned
  ansible.builtin.systemd:
    name: tuned
    state: started
    enabled: true
  failed_when: false

- name: Create tuned profile directory
  ansible.builtin.file:
    path: /etc/tuned/profiles/atomik
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy tuned profile
  ansible.builtin.template:
    src: tuned.conf.j2
    dest: /etc/tuned/profiles/atomik/tuned.conf
    owner: root
    group: root
    mode: "0644"
  notify: Apply tuned profile
