---

- name: Set default shell to fish
  ansible.builtin.user:
    name: "{{ atomik_user }}"
    shell: "{{ atomik_default_shell }}"

- name: Create fish config directory
  ansible.builtin.file:
    path: "/var/home/{{ atomik_user }}/.config/fish"
    state: directory
    owner: "{{ atomik_user }}"
    group: "{{ atomik_user }}"
    mode: "0755"

- name: Deploy fish config
  ansible.builtin.template:
    src: config.fish.j2
    dest: "/var/home/{{ atomik_user }}/.config/fish/config.fish"
    owner: "{{ atomik_user }}"
    group: "{{ atomik_user }}"
    mode: "0644"

- name: Create fish functions directory
  ansible.builtin.file:
    path: "/var/home/{{ atomik_user }}/.config/fish/functions"
    state: directory
    owner: "{{ atomik_user }}"
    group: "{{ atomik_user }}"
    mode: "0755"

- name: Deploy fish prompt
  ansible.builtin.template:
    src: fish_prompt.fish.j2
    dest: "/var/home/{{ atomik_user }}/.config/fish/functions/fish_prompt.fish"
    owner: "{{ atomik_user }}"
    group: "{{ atomik_user }}"
    mode: "0644"

- name: Install oh-my-fish
  ansible.builtin.shell: "test -d /var/home/{{ atomik_user }}/.local/share/omf || (curl -sL https://get.oh-my.fish -o /tmp/omf-install.fish && yes | fish /tmp/omf-install.fish)"
  become: true
  become_user: "{{ atomik_user }}"
  changed_when: false
  failed_when: false
